alias cls='clear'
alias ls='eza --icons'
alias python='python3'
alias pip='python3 -m pip'
alias secman='~/.bin/secman/build/secman'
alias wormhole='wormhole-rs'
alias mkcd='function _mkcd() { mkdir "$1" && cd "$1"; };_mkcd'
alias uni='cd ~/Desktop/DVergaraM/Universidad/2025_2'
alias java='"/c/Program Files/Java/jdk-21/bin/java"'
alias dev='cd ~/Desktop/DVergaraM/Dev/'
alias personal='cd ~/Desktop/DVergaraM/Personal/'
alias pdf='function _pdf(){ sumatrapdf "$1"; };_pdf'
alias readme='function _readme(){ glow "$1"; };_readme'
alias cwd='pwd'
alias back='function _back() { if [[ -f ~/.cwd ]]; then TARGET_DIR=$(cat ~/.cwd | tr -d '"'"'[:space:]'"'"'); if [[ -n "$TARGET_DIR" ]]; then cd "$TARGET_DIR"; else echo "Error: ~/.cwd file is empty."; return 1; fi; else echo "Error: ~/.cwd file not found. Use '"'"'cd'"'"' first to create it."; return 1; fi; }; _back'
